version: '3'
services:
  python-app:
    container_name: python-app-container
    build:
      context: ./fastApiProject
    ports:
      - "8000:8000"
    restart: always
  spring-app:
    container_name: spring-app-container
    build:
      context: ./BrainBox
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - python-app
  telegrambot:
    container_name: telegrambot-container
    build:
      context: ./telegramobot
    restart: always
    ports:
      - "3000:3000"
  supportbot:
    container_name: supportbot-container
    build:
      context: ./supportbot
    restart: always
    ports:
      - "3001:3001"